sonar.projectKey=appwrite-tests
sonar.projectName=Appwrite Tests

# Servidor local
sonar.host.url=http://localhost:9000

# Código fuente real
sonar.sources=app,src

# Tests
sonar.tests=tests/e2e

# Codificación
sonar.sourceEncoding=UTF-8

# Excluir carpetas pesadas
sonar.exclusions=vendor/**,docs/**,public/**,tmp/**

# e2e de las HU
sonar.test.inclusions=\
tests/e2e/Services/Users/**,\
tests/e2e/Services/Teams/**,\
tests/e2e/Services/Databases/Documents/Rows/**,\
tests/e2e/Services/Databases/Attributes/Columns/**